# Generated by Django 5.0 on 2024-01-01 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_message_chat_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advert',
            unique_together={('owner', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('advert', 'applicant')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('advert', 'reviewer')},
        ),
    ]
