# Generated by Django 5.0 on 2024-01-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_advert_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
