# Generated by Django 5.0 on 2024-01-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advert_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Finished', 'Finished')], default='Upcoming', max_length=10),
        ),
    ]
